spring:
  application:
    name: gateway-service
  profiles:
    active: dev
    include: secret
# 로깅 설정 추가
logging:
  level:
    com.ll.apigateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    reactor.netty: DEBUG
  file:
    name: ./logs/apigateway.log  # 로그 파일 위치
  pattern:
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true