server:
  port: 9000
spring:
  application:
    name: gateway-service
services:
  auth:
    url: http://auth:9010 # 인증 서비스 URL
  member:
    url: http://member:9020 # 회원 서비스 URL
  space:
    url: http://space:9030 # 스페이스 서비스 URL
  tech-interview:
    url: http://techinterview:9040 # 기술면접 서비스 URL
  onlinejudge:
    url: http://172.30.1.23:9050 # 코딩테스트 서비스 URL
  resume:
    url: http://resume:9060 # 자소서
  ai:
    url: http://ai:9090 # AI 서비스 URL
  admin:
    url: http://admin:9100 # admin 서비스 URL