spring:
  application:
    name: gateway-service
  profiles:
    active: dev
    include: secret

# 로깅 설정 추가
logging:
  level:
    com.ll.apigateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    reactor.netty: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always