server:
  port: 9000
spring:
  application:
    name: gateway-service
services:
  auth:
    url: http://172.30.1.23:9010 # 인증 서비스 URL
  member:
    url: http://172.30.1.23:9020 # 회원 서비스 URL
  space:
    url: http://172.30.1.23:9030 # 스페이스 서비스 URL
  tech-interview:
    url: http://172.30.1.23:9040 # 기술면접 서비스 URL
  ai:
    url: http://172.30.1.23:9090 # AI 서비스 URL