spring:
  application:
    name: gateway-service
  profiles:
    active: dev
    include: secret

# 로깅 설정 수정 (trace ID 추가)
logging:
  level:
    com.ll.apigateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    reactor.netty: DEBUG
  file:
    name: ./logs/apigateway.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [${spring.application.name:},%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
  # Zipkin 추적 설정 추가
  tracing:
    sampling:
      probability: 1.0  # 100% 샘플링 (개발환경용)
    excluded-paths:
      - "/actuator/**"
      - "/health/**"
      - "/metrics/**"
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  # 기존 Prometheus 설정
  prometheus:
    metrics:
      export:
        enabled: true
  # 기존 태그 설정
  observations:
    tags:
      application: ${spring.application.name}