spring:
  application:
    name: gateway-service
  profiles:
    active: dev
    include: secret

# 로깅 설정 추가
logging:
  level:
    root: INFO
    com.ll.apigateway: DEBUG  # 패키지명 맞게 수정
    com.ll.apigateway.filter: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG